### ISSUE TITLE
Unable to consume messages without increasing pollDuration in consumer settings

### ISSUE THREAD

**Issue by brokenjacobs** [kestra-io/plugin-kafka#73] opened 2024-04-22 21:52 UTC
### Expected Behavior

I expected a consumer group to be created, and the topics (either topic or topicPattern) to show up in that consumer group with appropriate lag. 

### Actual Behaviour

What happened is the consumer group gets created, but it is always empty. And no messages get consumed from my topics. When we increased pollDuration to 10s things started working as expected. We reproduced this with the trigger and the consumer task. With topic (2 topics as a list of strings) and a topicPattern regex (that matched 81 topics, per the kafka debug logs on kestra).

### Steps To Reproduce

We have a largish kafka environment with many topics and partitions. I assume this is necessary to reproduce the issue.

### Environment Information

- Kestra Version: v0.16.2
- Plugin version: v0.16.0
- Operating System (OS / Docker / Kubernetes): Kubernetes / GKE v1.28.7-gke.1026000
- Java Version (If not docker): 17 as in the container

**Comment by anna-geller** [comment] 2024-05-08 15:20
Hey, sorry for getting back to you late on this. 

Could you share the flow that fails for you? are you using a Kafka trigger or task?

Regarding `pollDuration`: we've recently merged Realtime Trigger that will allow you to react to Kafka messages in real-time without polling https://github.com/kestra-io/plugin-kafka/commit/7c26646df3f95fb810db58de46becd65ca6219de -- it's available in Beta on the develop image

**Comment by anna-geller** [comment] 2024-05-24 12:01
closing as: 
- we will release RealtimeTrigger for Kafka in ~1 week (4th of June 2024) - this should no longer have that issue as it triggers one execution per message 
- we cannot reproduce without a workflow example -- if you still see the issue, please reopen and add a flow example

**Closed by anna-geller** 2024-05-24 12:01 UTC
Labels: bug
